language: ruby
rvm:
  - 2.2.1
  - 2.1.5
  - 2.0.0
  - 1.9.3
script:
  - bundle exec rspec
  - bundle exec cucumber
addons:
  code_climate:
    repo_token: a2ffd6e9333c7bd186a6d98e58e582b0ffb1f623e3c788a5656986ddc355c350
